import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// --- [NEW] ReservationProvider import ---
import { ReservationProvider } from "@/contexts/ReservationContext"; // 경로 확인! (@/는 src/ 또는 프로젝트 루트)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* --- [MODIFIED] ReservationProvider로 감싸기 --- */}
        <ReservationProvider>
          {children} {/* 페이지 내용이 여기에 렌더링 됩니다 */}
        </ReservationProvider>
        {/* --- [END MODIFICATION] --- */}
      </body>
    </html>
  );
}